#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


picom &
feh --bg-scale /home/alexey/Imágenes/4k-Among-Trees-forest-trees-2185585.png
/home/alexey/.config/polybar/./launch.sh &
wmname LG3D &
bspc config border_width 0
#xrandr -s 1920x1080
#setxkbmap es
