#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc config focused_border_color "#00fbff"

picom &
#feh --bg-scale /home/alexey/Imágenes/minimalist-landscape.png
#feh --bg-scale /home/alexey/Imágenes/hogwarts-legacy.jpg
#feh --bg-scale /home/alexey/Imágenes/digital-art-abstract-geometry-gaming.jpg
#feh --bg-scale /home/alexey/Imágenes/3840x2160-among-trees-night-is-coming-4k_1690551937.jpg
feh --bg-scale /home/alexey/Imágenes/abstract.png
/home/alexey/.config/polybar/./launch.sh &
wmname LG3D &
bspc config border_width 0
flameshot &
xsetroot -cursor_name left_ptr &
#xrandr -s 1920x1080
#setxkbmap es
